name: live_admin_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  cloud_firestore: ^3.1.5
  fluttertoast: ^8.0.8
  image_picker: ^0.8.4+4
  dotted_border: ^2.0.0+2
  firebase_storage: ^10.2.4
  cached_network_image: ^3.2.0
  photo_view: ^0.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.2"
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/app_logo.png"

  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/logo/

  fonts:
    - family: niladriFontLite
      fonts:
        - asset: assets/fonts/li_Niladri_Nodia_ANSI_V1.ttf
    #        style: italic

    - family: barkatFontBold
      fonts:
        - asset: assets/fonts/li_Shohid_Barkat_ANSI_V2.ttf
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
